version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/certs:/etc/nginx/certs
      - ../nginx/logs:/var/log/nginx
    networks:
      - web-network

networks:
  web-network:
    external: true
